# Copyright 2017, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License")
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: envtestt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: envtestt
    spec:
      containers:
      - name: envtestt
        image: gcr.io/<PROJECT_ID>/envtestt
        ports:
        - containerPort: 3000
        env:
        - name: LANGUAGE
          value: "English"
        - name: API_KEY
          value: "123-456-789"
